self-hosted-runner:
  labels:
    - blacksmith-2vcpu-ubuntu-2404
    - blacksmith-4vcpu-ubuntu-2404
    - blacksmith-8vcpu-ubuntu-2404
    - blacksmith-16vcpu-ubuntu-2404
    - blacksmith-32vcpu-ubuntu-2404
    - blacksmith-2vcpu-windows-2025
    - blacksmith-4vcpu-windows-2025
    - blacksmith-8vcpu-windows-2025
    - blacksmith-16vcpu-windows-2025
    - blacksmith-32vcpu-windows-2025
