# Changes here will be overwritten by Copier.
_commit: 2.5.0
_src_path: gh:ichoosetoaccept/copier-uv-bleeding
author_email: ismar@gmail.com
author_fullname: Ismar Iljazovic
author_username: ichoosetoaccept
copyright_license: ISC
project_description: A model context protocol server for interacting with Unblu deployments.
project_name: unblu-mcp
publish_to_pypi: false
